name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # basically useless
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  # für globalen state
  shared_preferences: ^2.0.15
  # path utils (basename, dirname, join, usw.)
  path: ^1.8.2
  # um den Projektordner zu wählen
  file_picker: ^10.3.8
  # um den text aus PDFs zu extrahieren
  syncfusion_flutter_pdf: ^32.1.21
  # für das Accordion
  getwidget: ^7.0.0
  # Zum Anzeigen von PDFs (ungenutzt)
  # pdfx: ^2.3.0
  # Syntax Highlighting
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  # code editor
  flutter_code_editor: ^0.3.5
  # Zip utils
  archive: ^4.0.7
  # context menu support
  contextmenu: ^3.0.0
  # get desktop monitor size
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  
flutter_launcher_name:
  name: "Tut Tool"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
